### ISSUE TITLE
Enum values should be specified explicitly

### ISSUE THREAD

**Issue by bordecal** [SonarSource-VisualStudio/sonarlint-roslyn-analyzer#706]
... due to constant dereferencing issue (see "Robust Programming" section at https://msdn.microsoft.com/en-us/library/sbbt4032.aspx).

**Comment by tvsonar** [comment]
@bordecal I think this rule would be very noisy. For `[Flags]` enums it is already implemented though: http://www.sonarlint.org/visualstudio/rules/index.html#version=1.6.0&ruleId=S2345

In any case, I'm adding the rule-idea label, we'll need to check how noisy it is.

**Comment by bordecal** [comment]
@tvsonar: By "noisy", do you mean false positives?  If so, this really shouldn't be a problem when analyzing source as opposed to IL (one of the reasons that it couldn't be implemented as an FxCop rule in the past).  If you mean that folks won't want to apply it, a couple of considerations:

* It could be disabled by folks that don't want to apply this level of rigour.
* It could potentially be made to only apply to public enums (hopefully via configuration vs as the only behaviour!) to narrow the focus.

**Comment by tvsonar** [comment]
@bordecal Yep, I'm thinking about people who don't want to apply this rule. It's true that rules can be turned off, but we try not to be annoying, so internally we say that any controversial rule must be turned off by default. (We get complaints about being too noisy, and that's one reason why we adjusted the default activation of rules in the [1.6.0](https://github.com/SonarSource/sonarlint-vs/issues?q=milestone:1.6.0) release.)

So, I think this rule would need to be disabled by default. And then it's not on the top of our priority list, because we can still add rules that are enabled by default, thus adding more value to the product.

I gave it a quick try though through the S2345 rule without checking for the `Flags`, and the ruling test resulted in 135 matches vs. the 1 match with the `Flags` attribute. (It's a huge difference, but I was expecting a lot more.)
