### ISSUE TITLE
rules show up with vsix, but not with nuget

### ISSUE THREAD

**Issue by kevinpdpath** [SonarSource-VisualStudio/sonarlint-roslyn-analyzer#735]
I first installed the SonarLint VS Extension. When I then viewed my ruleset, I saw SonarLint.CSharp with all of its rules.

I then saw that there was a nuget package, so I decided to uninstall the vsix and install the nuget package instead. Now when I view my ruleset, the only rule under SonarLint.CSharp is S1481 and its name is "Unknown".

I am using SonarLint 1.6.0. I also have StyleCop.Analyzers 1.0.0-rc2 which is working fine.

**Comment by dbolkensteyn** [comment]
@kevinpdpath I only can reproduce this if I open the *.ruleset directly, without first loading the project depending on the SonarLint VS NuGet package.

Indeed, Visual Studio first needs to load the SonarLint VS assemblies in order to be able to fetch the rule titles from the IDs specified in the .ruleset file.
